### ISSUE TITLE
compilation error: too many initializers for ‘op::CvMatToOpInput’

### ISSUE THREAD

**Issue by AlexLuya** [srianant/computer_vision#1]
Hello,I have
   gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 
   opencv 3.1
   openpose 2017-10-30 master
   and have added blow three lines to openpose_recognition.cpp
```
  // GFlags: DEFINE_bool, _int32, _int64, _uint64, _double, _string
#include <gflags/gflags.h>
// Allow Google Flags in Ubuntu 14
#ifndef GFLAGS_GFLAGS_H_
    namespace gflags = google;
#endif
```
  for error:
`expected constructor, destructor, or type conversion before ‘(’ token DEFINE_int32`
and the compile,got this error:
`   openpose_recognition.cpp:240:93: error: too many initializers for ‘op::CvMatToOpInput’`
for line:
   ` op::CvMatToOpInput cvMatToOpInput{netInputSize, FLAGS_num_scales, (float)FLAGS_scale_gap};`

**Comment by srianant** [comment]
Hi,
Thanks for trying out. 
I would suggest first try successfully compile openpose repo first, before integrating changes from this repo.

**Comment by AlexLuya** [comment]
@srianant ,openpose works fine,I got it work for six months already,I think you may used an old version openpose,

**Comment by srianant** [comment]
@AlexLuya this repo was compiled with OpenPose 1.0.0 version that has hand rendering support, which is required for hand gesture. I think this was released sometime in July/Aug 2017 by CMU team. If you are using more recent, its possible they have added few more. 
You can check: 
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/release_notes.md

**Comment by AlexLuya** [comment]
Unfortunately,openpose guys haven't maintain any versioning mechanism,there is no way to get v1.0,is there any possible you will update your project to compatible with current openpose?If not,would you please give me some tips so I will try it by myself

**Comment by angelbeibei** [comment]
@AlexLuya 
Hello,Have you solved the error? Please help me,Thanks
