### ISSUE TITLE
Can it learn with the original data set.

### ISSUE THREAD

**Issue by taka0913** [srianant/computer_vision#10]
If it is possible, could you teach me how to make a dataset and how to make it learn?
Many thanks

**Comment by taka0913** [comment]
I read the code in detail.
It seems like learning by running "rnn_lstm_classifier.py".

There are things I do not know about dataset.
The contents of "pose_samples_raw.txt" is 311 * 180.
I think that 311 is the number of samples.
But 180 is too much if it is the keypoint of one sample.
What do the 180 numbers in the row mean?

**Comment by hufo1** [comment]
180=5*36

**Comment by houdinisparks** [comment]
can someone explain why theare are 36 keypoints for the pose? i though the coco dataset only follow 18.

**Comment by srianant** [comment]
5 frames. 36 keypoints per frame.

**Comment by yurochang** [comment]
> I read the code in detail.
> It seems like learning by running "rnn_lstm_classifier.py".
> 
> There are things I do not know about dataset.
> The contents of "pose_samples_raw.txt" is 311 * 180.
> I think that 311 is the number of samples.
> But 180 is too much if it is the keypoint of one sample.
> What do the 180 numbers in the row mean?

Have you successfully use your own data?
