### ISSUE TITLE
only able to compile with Openpose 1.0.1

### ISSUE THREAD

**Issue by AlverGant** [srianant/computer_vision#17]
Probably there is a mistake in the installation instructions, I was only able to compile with Openpose 1.0.1 and not 1.0.0 as stated.

**Comment by AlverGant** [comment]
Actually version 1.0.2 is the way to go, I was able to compile and to run openpose_recognition.bin without problems.
With version 1.0.0 I had issues during compilation
With version 1.0.1 no problems during compilation but openpose_recognition issues a memory corruption and segmentation fault

**Comment by srianant** [comment]
Thanks for posting your findings @AlverGant. Really appreciate it. Will update readme.
