### ISSUE TITLE
Is CMAKE install supported?

### ISSUE THREAD

**Issue by kaisark** [srianant/computer_vision#18]
It looks like the manual Makefile compilation method is now deprecated in openpose and has been replaced by CMAKE. Instead of using makefiles, can your usercode be generated via CMAKE using CMakeLists.txt (e.g. ./src/openpose/face/CMakeLists.txt)? 

Openpose New Install Method: (Cmake)
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#cmake-command-line-configuration-ubuntu-only

Openpose Old Install Method: (Makefile.config - Makefile)
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation_deprecated.md

**Comment by srianant** [comment]
No plans to support CMAKE.
