### ISSUE TITLE
Does this run on only videos or can you do live, real-time classification from a streaming webcam?

### ISSUE THREAD

**Issue by molecule** [srianant/computer_vision#20]
This looks great for my purposes. I am a researcher at UC Berkeley and I'd like to use a full-body gesture/pose recognition system for one person for an ongoing project.

Just one question: Does this run on only videos or can you do live, real-time classification from a streaming webcam?

Thanks,
Molly

**Comment by srianant** [comment]
File: https://github.com/srianant/computer_vision/blob/master/openpose/examples/user_code/openpose_recognition.cpp

Above file allow two parameters camera and video_path. Video streaming is not supported. 

Good luck with your research.
