### ISSUE TITLE
examples/user_code/openpose_recognition.cpp: In function ‘int openPoseRecognition()’:

### ISSUE THREAD

**Issue by hufo1** [srianant/computer_vision#5]
examples/user_code/openpose_recognition.cpp:235:93: error: too many initializers for ‘op::CvMatToOpInput’
     op::CvMatToOpInput cvMatToOpInput{netInputSize, FLAGS_num_scales, (float)FLAGS_scale_gap};
                                                                                             ^
compilation terminated due to -Wfatal-errors.
Makefile:478: recipe for target '.build_release/examples/user_code/openpose_recognition.o' failed
make: *** [.build_release/examples/user_code/openpose_recognition.o] Error 1
How to solve it?

**Comment by AlexLuya** [comment]
[openpose_recognition-changed.txt](https://github.com/srianant/computer_vision/files/1449545/openpose_recognition-changed.txt)
@hufo1 ,please refer to https://github.com/srianant/computer_vision/issues/1, in a word,this repository is based on openpose 1.0,and you may using a new version openpose(master version is 1.2 right now),I have updated  openpose_recognition like attachment,and it will compiled successfully,but I got blow error when running it:
```
erminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  unsupported version
```
If you can got this repository working,please tell me:alex.luya@yahoo.com

**Comment by srianant** [comment]
Thanks @AlexLuya. 
@hufo1  this source is based on openpose 1.0.0. @AlexLuya have ported to latest version please try that.
