### ISSUE TITLE
'boost::archive::archive_exception' what(): unsupported version

### ISSUE THREAD

**Issue by AlexLuya** [srianant/computer_vision#6]
(I have asked this question before,but you just give me "yes,please")

When running openpose_recognition.bin,I got this:

```
OpenPose/DLIB Gesture, Action and Face Recognition.
resolution: 640x480
net_resolution: 656x368
handNetInputSize: 368x368
face_net_resolution: 368x368
cCamera Resolution set to: 640x480
Push following keys:
p for pause sample generation
f for generating face samples
t for train samples
c for continue camera feed
h for display key commands
q for quit program
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  unsupported version
```
by the way,I have boost 1.58.1 in my ubuntu 16.04,and 

**.../build/examples/openpose/openpose.bin works well in both versions which built from default Makefile/Makefile.config and the corresponded files provided by this repository**

After 3 days struggling,I still can't figure out a way to solve this problem,so please help me

**Comment by srianant** [comment]
@AlexLuya  do you have below changes in Makefile ?
> LIBRARIES += glog gflags boost_system boost_filesystem m hdf5_hl hdf5 caffe <== comment out
> LIBRARIES += glog gflags boost_system boost_serialization boost_filesystem m hdf5_hl hdf5 caffe

This is very specific to your environment/installation. 
Please try serialize/de-serialize using boost (for specific version) library with examples in link below and make sure your binaries are linked as expected.
http://www.boost.org/doc/libs/1_65_1/libs/serialization/doc/tutorial.html

Sorry, I will not be able to help much here.

**Comment by AlexLuya** [comment]
@srianant,After replacing ::archive 14 with ::archive 12 in all txt files,this problem gone

**Comment by Harry-675** [comment]
@AlexLuya I met similar question, what do you mean by replacing ::archive 14 with ::archive 12 in all txt files? Which txt file?

**Comment by zeyuanlicbpm** [comment]
@Harry-675  in the folder train_data
