### ISSUE TITLE
How can I transform 2D keypoints output from Openpose to sample data? 

### ISSUE THREAD

**Issue by luckyli1984** [srianant/computer_vision#9]
Hi  
I try to train my own data, but I don't understand how to transform 2D keypoint outputs from Openpose to sample data like yours in train_data/pose/pose_samples_raw.txt.
Can you show me how to do it? Thanks

**Comment by srianant** [comment]
Method "getSamplesFromPoseKeypoints" in openpose/src/openpose/user_code/pose_model.cpp is what you need to look into. "pose_sample" vector holds the sample data.

**Comment by yurochang** [comment]
> Hi
> I try to train my own data, but I don't understand how to transform 2D keypoint outputs from Openpose to sample data like yours in train_data/pose/pose_samples_raw.txt.
> Can you show me how to do it? Thanks

Have you successfully use your own data?
